name: Lint

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          uv sync

      - name: Run ruff (linter)
        run: |
          uv run ruff check src/ tests/

      - name: Run ruff (formatter check)
        run: |
          uv run ruff format --check src/ tests/

      - name: Run mypy (type checker)
        run: |
          uv run mypy src/ --strict

